# Generated by Django 5.2.15 on 2026-07-03 03:07

import core.ids
import django.db.models.deletion
import identity.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=identity.models._default_user_public_id, max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('apple_sub', models.CharField(max_length=255, null=True, unique=True)),
                ('google_sub', models.CharField(max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('install_id', models.CharField(max_length=64, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], max_length=16)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('last_seen_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(max_length=16)),
                ('family_id', models.UUIDField(db_index=True, default=core.ids.uuid7)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('last_used_at', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='identity.device')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='identity.refreshtoken')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
