# Generated by Django 5.2.15 on 2026-07-03 03:52

import core.ids
import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'address'), name='uniq_venue_name_address')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=events.models._default_event_public_id, max_length=32, unique=True)),
                ('import_ref', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('sales_start_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('on_sale', 'On Sale'), ('live', 'Live'), ('ended', 'Ended')], db_index=True, default='draft', max_length=16)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False)),
                ('host_name', models.CharField(blank=True, default='', max_length=200)),
                ('host_verified', models.BooleanField(default=False)),
                ('age_restriction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allow_refunds', models.BooleanField(default=True)),
                ('allow_transfers', models.BooleanField(default=True)),
                ('social_energy_override', models.JSONField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='uniq_saved_event_user_event')],
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_ref', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('price_cents', models.PositiveIntegerField()),
                ('quantity_total', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_sold__lte', models.F('quantity_total'))), name='tier_sold_lte_total'), models.UniqueConstraint(condition=models.Q(('import_ref', ''), _negated=True), fields=('event', 'import_ref'), name='uniq_tier_event_import_ref')],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('import_ref', ''), _negated=True), fields=('import_ref',), name='uniq_event_import_ref'),
        ),
    ]
