# Generated by Django 5.2.15 on 2026-07-03 13:53

import core.ids
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_ref', models.CharField(blank=True, default='', max_length=64)),
                ('nonprofit_name', models.CharField(max_length=200)),
                ('cause_title', models.CharField(max_length=200)),
                ('cause_description', models.TextField(blank=True, default='')),
                ('goal_cents', models.PositiveBigIntegerField()),
                ('raised_cents', models.PositiveBigIntegerField(default=0)),
                ('donor_count', models.PositiveIntegerField(default=0)),
                ('suggested_amounts_cents', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='host_is_nonprofit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='refund_policy_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='quantity_held',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='tickettier',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_sold__lte', django.db.models.expressions.CombinedExpression(models.F('quantity_total'), '-', models.F('quantity_held')))), name='tier_sold_plus_held_lte_total'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_campaign', to='events.event'),
        ),
    ]
