# Generated by Django 5.2.15 on 2026-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_donationcampaign_event_host_is_nonprofit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='access_tier',
            field=models.CharField(default='general_admission', max_length=32),
        ),
    ]
