"""
Server-authoritative pricing engine (Phase 3 / W1 — locked fee model).

Buyer-facing model (master plan, locked):
    5% ECHO platform fee + 2.9% + $0.30 payment processing + tax,
    nonprofit waiver removes the platform fee only (processing always applies),
    donations add their own 2.9% + $0.30 processing fee on top.

This module deliberately mirrors the client engine's float sequence
(frontend/services/pricingEngine.ts computeCheckoutFees /
donationCampaignService.computeDonationProcessingFee): compute in dollar
floats, round each component to 2 decimals with JS Math.round semantics
(half away from zero for the non-negative values money uses), then convert
to integer cents. JS and Python both use IEEE-754 doubles, so identical
operation order gives identical results — checkout/tests/test_pricing.py
proves it against a fixture generated by the client engine itself
(frontend/scripts/dump-pricing-parity.ts) before the client engine is
demoted to display logic.

Rates come from settings (the same constants /v1/config/public serves).
"""

import math
from dataclasses import dataclass

from django.conf import settings


def _round2(value: float) -> float:
    """JS `Math.round(value * 100) / 100` for non-negative values."""
    return math.floor(value * 100 + 0.5) / 100


def _to_cents(dollars: float) -> int:
    """JS `Math.round(dollars * 100)` for non-negative values."""
    return math.floor(dollars * 100 + 0.5)


@dataclass(frozen=True)
class PricingBreakdown:
    """All values in integer cents (locked rule)."""

    subtotal_cents: int
    platform_fee_cents: int
    processing_fee_cents: int
    tax_cents: int
    donation_cents: int
    donation_fee_cents: int
    total_cents: int

    @property
    def fees_cents(self) -> int:
        """The wire's combined "Service & processing fee"."""
        return self.platform_fee_cents + self.processing_fee_cents


def compute_pricing(
    subtotal_cents: int,
    *,
    nonprofit_host: bool = False,
    donation_cents: int = 0,
    tax_rate: float | None = None,
) -> PricingBreakdown:
    """Price a checkout: ticket subtotal + fees + tax, plus an optional
    donation line with its own processing fee.

    `subtotal_cents` is quantity-folded (unit price x quantity) and
    `donation_cents` is the donor-chosen amount; both must be >= 0.
    """
    if subtotal_cents < 0 or donation_cents < 0:
        raise ValueError("pricing amounts must be non-negative")
    if tax_rate is None:
        tax_rate = settings.ECHO_DEFAULT_TAX_RATE

    processing_flat = settings.ECHO_PAYMENT_PROCESSING_FLAT_CENTS / 100

    # Mirror of computeCheckoutFees(subtotal_dollars, nonprofit_host, tax_rate).
    subtotal = subtotal_cents / 100
    platform_fee = 0.0 if nonprofit_host else _round2(subtotal * settings.ECHO_PLATFORM_FEE_RATE)
    processing_fee = _round2(subtotal * settings.ECHO_PAYMENT_PROCESSING_RATE + processing_flat)
    tax = _round2(subtotal * tax_rate)

    # Mirror of computeDonationProcessingFee(donation_dollars).
    donation = donation_cents / 100
    donation_fee = (
        _round2(donation * settings.ECHO_PAYMENT_PROCESSING_RATE + processing_flat)
        if donation_cents > 0
        else 0.0
    )

    platform_fee_cents = _to_cents(platform_fee)
    processing_fee_cents = _to_cents(processing_fee)
    tax_cents = _to_cents(tax)
    donation_fee_cents = _to_cents(donation_fee)

    return PricingBreakdown(
        subtotal_cents=subtotal_cents,
        platform_fee_cents=platform_fee_cents,
        processing_fee_cents=processing_fee_cents,
        tax_cents=tax_cents,
        donation_cents=donation_cents,
        donation_fee_cents=donation_fee_cents,
        # Exact sum of the serialized components — wire rows always add up.
        # The parity fixture proves this also equals the client's displayed
        # total for the whole grid.
        total_cents=(
            subtotal_cents
            + platform_fee_cents
            + processing_fee_cents
            + tax_cents
            + donation_cents
            + donation_fee_cents
        ),
    )
