# Generated by Django 5.2.15 on 2026-07-03 13:53

import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_donationcampaign_event_host_is_nonprofit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckoutIntent',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('requires_verification', 'Requires Verification'), ('requires_payment', 'Requires Payment'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='requires_payment', max_length=24)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal_cents', models.PositiveIntegerField()),
                ('platform_fee_cents', models.PositiveIntegerField()),
                ('processing_fee_cents', models.PositiveIntegerField()),
                ('tax_cents', models.PositiveIntegerField()),
                ('donation_cents', models.PositiveIntegerField(default=0)),
                ('donation_fee_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField()),
                ('age_verification_required', models.BooleanField(default=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('hold_returned_at', models.DateTimeField(blank=True, null=True)),
                ('donation_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_intents', to='events.donationcampaign')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_intents', to='events.event')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_intents', to='events.tickettier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_intents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('processing_fee_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('refunded', 'Refunded')], default='succeeded', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='events.donationcampaign')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='checkout.checkoutintent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='checkoutintent',
            index=models.Index(fields=['status', 'expires_at'], name='intent_status_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkoutintent',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_intent_id', ''), _negated=True), fields=('stripe_payment_intent_id',), name='uniq_intent_stripe_payment_intent'),
        ),
    ]
