# Generated by Django 5.2.15 on 2026-07-03 15:12

import core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCredential',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(max_length=64)),
                ('nfc_credential_id', models.CharField(max_length=64, unique=True)),
                ('validation_token', models.TextField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('minted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='tickets.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
