"""W1 pricing engine: bit-for-bit parity with the client engine (fixture
generated by frontend/scripts/dump-pricing-parity.ts from the real
pricingEngine.ts outputs) plus the engine's own invariants."""

import json
from pathlib import Path

import pytest

from checkout.pricing import compute_pricing

PARITY_FIXTURE = Path(__file__).parent / "pricing_parity.json"


def _load_cases():
    return json.loads(PARITY_FIXTURE.read_text())["cases"]


class TestClientParity:
    def test_fixture_present_and_broad(self):
        cases = _load_cases()
        assert len(cases) >= 500
        assert any(case["nonprofit_host"] for case in cases)
        assert any(case["donation_cents"] > 0 for case in cases)

    def test_component_parity_over_full_grid(self):
        mismatches = []
        for case in _load_cases():
            expected = case["expected"]
            actual = compute_pricing(
                case["subtotal_cents"],
                nonprofit_host=case["nonprofit_host"],
                donation_cents=case["donation_cents"],
            )
            got = {
                "platform_fee_cents": actual.platform_fee_cents,
                "processing_fee_cents": actual.processing_fee_cents,
                "service_fee_cents": actual.fees_cents,
                "tax_cents": actual.tax_cents,
                "donation_fee_cents": actual.donation_fee_cents,
                "ticket_total_cents": actual.subtotal_cents
                + actual.fees_cents
                + actual.tax_cents,
            }
            if got != expected:
                mismatches.append((case, got))
        assert not mismatches, f"{len(mismatches)} parity mismatch(es); first: {mismatches[0]}"

    def test_total_is_exact_component_sum(self):
        for case in _load_cases():
            actual = compute_pricing(
                case["subtotal_cents"],
                nonprofit_host=case["nonprofit_host"],
                donation_cents=case["donation_cents"],
            )
            assert actual.total_cents == (
                actual.subtotal_cents
                + actual.platform_fee_cents
                + actual.processing_fee_cents
                + actual.tax_cents
                + actual.donation_cents
                + actual.donation_fee_cents
            )


class TestEngineRules:
    def test_locked_fee_model_at_a_known_price(self):
        # $120.00: platform $6.00, processing $3.78, tax $10.20 (8.5%).
        pricing = compute_pricing(12_000)
        assert pricing.platform_fee_cents == 600
        assert pricing.processing_fee_cents == 378
        assert pricing.tax_cents == 1020
        assert pricing.total_cents == 12_000 + 600 + 378 + 1020

    def test_nonprofit_waiver_removes_platform_fee_only(self):
        pricing = compute_pricing(12_000, nonprofit_host=True)
        assert pricing.platform_fee_cents == 0
        assert pricing.processing_fee_cents == 378  # processing always applies
        assert pricing.tax_cents == 1020

    def test_donation_carries_its_own_processing_fee(self):
        pricing = compute_pricing(0, donation_cents=1000)
        # $10 donation: 2.9% + $0.30 = $0.59
        assert pricing.donation_fee_cents == 59
        assert pricing.donation_cents == 1000

    def test_zero_donation_has_no_fee(self):
        assert compute_pricing(5000).donation_fee_cents == 0

    def test_negative_amounts_rejected(self):
        with pytest.raises(ValueError):
            compute_pricing(-1)
        with pytest.raises(ValueError):
            compute_pricing(100, donation_cents=-1)
