import { Event, Ticket, User } from '../types';
import { GENERATED_EVENTS } from './mockEvents';
import { EXTRA_EVENTS } from './mockEventsNational';
import { MOCK_HOST_EVENTS } from './mockHostEventSuite';

const getDate = (daysFromNow: number, hour = 19, minute = 0) => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

// Original hand-crafted events (kept for backward compat with existing ticket refs)
const ORIGINAL_EVENTS: Event[] = [
  {
    id: 'evt_001',
    title: 'Nightfall Festival',
    description: 'An elevated electronic night with immersive visuals, trusted entry, and premium group arrival flow.',
    venue_id: 'ven_001',
    venue_name: 'The Warehouse',
    venue_address: '123 Industrial Ave, Seattle, WA',
    start_time: getDate(0, 20),
    end_time: getDate(1, 2),
    category: 'music',
    image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3',
    ticket_types: [
      { id: 'tkt_001', name: 'General Admission', price: 75, available: 250 },
      { id: 'tkt_002', name: 'VIP Access', price: 150, available: 50 },
    ],
    status: 'on_sale',
    age_restriction: 21,
    is_featured: true,
    host_name: 'Electric Vibes',
    host_verified: true,
    allow_refunds: true,
    allow_transfers: true,
  },
  {
    id: 'evt_002',
    title: 'Jazz in the Garden',
    description: 'Smooth jazz outdoors with lounge seating, curated food, and refined pacing from arrival through closeout.',
    venue_id: 'ven_002',
    venue_name: 'Botanical Gardens',
    venue_address: '456 Park Lane, Seattle, WA',
    start_time: getDate(0, 18),
    end_time: getDate(0, 22),
    category: 'music',
    image_url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629',
    ticket_types: [
      { id: 'tkt_003', name: 'Lawn Seating', price: 35, available: 500 },
      { id: 'tkt_004', name: 'Table Service', price: 120, available: 20 },
    ],
    status: 'live',
    age_restriction: null,
    host_name: 'Abbe Collective',
    host_verified: true,
    allow_refunds: true,
    allow_transfers: true,
  },
  {
    id: 'evt_003',
    title: 'Art & Soul Exhibition',
    description: 'Contemporary gallery experience with timed access and a calm, high-trust check-in flow.',
    venue_id: 'ven_003',
    venue_name: 'Modern Art Museum',
    venue_address: '789 Culture Blvd, Seattle, WA',
    start_time: getDate(1, 10),
    end_time: getDate(1, 20),
    category: 'art',
    image_url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e',
    ticket_types: [{ id: 'tkt_005', name: 'General Entry', price: 25, available: 200 }],
    status: 'on_sale',
    age_restriction: null,
    host_name: 'Seattle Modern',
    host_verified: true,
    allow_refunds: true,
    allow_transfers: true,
    donation_campaign: {
      id: 'camp_gff_scholarship_evt003',
      nonprofitName: 'Golden Futures Foundation',
      causeTitle: 'Youth Scholarship Fund',
      causeDescription: 'Help fund scholarships, mentorship, and community access programs for local students.',
      goalAmount: 5000,
      raisedAmount: 1240,
      donorCount: 47,
      suggestedAmounts: [5, 10, 25],
      impactLabels: [
        { amount: 5, label: 'Supports supplies' },
        { amount: 10, label: 'Supports mentorship' },
        { amount: 25, label: 'Scholarship contribution' },
      ],
      publicPageEnabled: true,
      allowPublicNameOptIn: false,
      closesAtEventCloseout: true,
      status: 'active',
    },
  },
  {
    id: 'evt_004',
    title: 'Comedy Night Live',
    description: 'Fast-paced stand-up with premium seating tiers and instant wallet delivery.',
    venue_id: 'ven_004',
    venue_name: 'The Laugh Factory',
    venue_address: '321 Humor St, Seattle, WA',
    start_time: getDate(0, 21),
    end_time: getDate(0, 23),
    category: 'comedy',
    image_url: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca',
    ticket_types: [{ id: 'tkt_006', name: 'Standard', price: 30, available: 100 }],
    status: 'on_sale',
    age_restriction: 18,
    host_name: 'Live Laugh Events',
    host_verified: true,
    allow_refunds: true,
    allow_transfers: true,
  },
  {
    id: 'evt_005',
    title: 'Tech Innovators Summit',
    description: 'A polished conference experience with verified hosts, role-based access, and enterprise-grade entry.',
    venue_id: 'ven_005',
    venue_name: 'Convention Center',
    venue_address: '555 Tech Drive, Seattle, WA',
    start_time: getDate(2, 9),
    end_time: getDate(2, 18),
    category: 'tech',
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87',
    ticket_types: [
      { id: 'tkt_007', name: 'Day Pass', price: 199, available: 500 },
      { id: 'tkt_008', name: 'Full Conference', price: 499, available: 200 },
    ],
    status: 'on_sale',
    age_restriction: null,
    is_featured: true,
    host_name: 'Future Systems',
    host_verified: true,
    allow_refunds: true,
    allow_transfers: true,
  },
  {
    id: 'evt_006',
    title: 'Food & Wine Festival',
    description: 'Signature tasting event with premium partner hosts and an elevated guest journey.',
    venue_id: 'ven_006',
    venue_name: 'Waterfront Plaza',
    venue_address: '888 Harbor View, Seattle, WA',
    start_time: getDate(5, 12),
    end_time: getDate(5, 22),
    category: 'food',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1',
    ticket_types: [
      { id: 'tkt_009', name: 'Tasting Pass', price: 85, available: 300 },
      { id: 'tkt_010', name: 'Premium Experience', price: 175, available: 75 },
    ],
    status: 'on_sale',
    age_restriction: 21,
    host_name: 'Waterfront Social',
    host_verified: true,
    allow_refunds: true,
    allow_transfers: true,
  },
  {
    id: 'evt_007',
    title: 'Sunset Yoga Session',
    description: 'A restorative community rooftop session with frictionless free entry and calm arrival flow.',
    venue_id: 'ven_007',
    venue_name: 'Rooftop Garden',
    venue_address: '100 Sky High Ave, Seattle, WA',
    start_time: getDate(0, 17),
    end_time: getDate(0, 19),
    category: 'community',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b',
    ticket_types: [{ id: 'tkt_011', name: 'Drop-in', price: 0, available: 30 }],
    status: 'live',
    age_restriction: null,
    host_name: 'Elevate Wellness',
    host_verified: true,
    allow_refunds: true,
    allow_transfers: true,
  },
  {
    id: 'evt_008',
    title: 'Indie Film Premiere',
    description: 'A premiere-night experience designed for premium discovery, save, and share behavior.',
    venue_id: 'ven_008',
    venue_name: 'Paramount Theatre',
    venue_address: '200 Cinema Lane, Seattle, WA',
    start_time: getDate(1, 19),
    end_time: getDate(1, 22),
    category: 'film',
    image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba',
    ticket_types: [{ id: 'tkt_012', name: 'General Admission', price: 18, available: 400 }],
    status: 'on_sale',
    age_restriction: null,
    host_name: 'Cinema House',
    host_verified: true,
    allow_refunds: true,
    allow_transfers: true,
  },
];

// Merge: original events + 100 generated events (deduped by ID)
const seenIds = new Set<string>();
const DEDUPED_MOCK_EVENTS: Event[] = [...ORIGINAL_EVENTS, ...MOCK_HOST_EVENTS, ...GENERATED_EVENTS, ...EXTRA_EVENTS].filter((e) => {
  if (seenIds.has(e.id)) return false;
  seenIds.add(e.id);
  return true;
});

// Home/discovery surfaces use still photos only. Event Details may use optional detail_media_* fields when hosts provide video/photo media.
export const MOCK_EVENTS: Event[] = DEDUPED_MOCK_EVENTS;

export const MOCK_USER: User = {
  id: 'usr_001',
  email: 'demo@echo.events',
  name: 'Demo User',
  phone: '+1 (555) 123-4567',
  avatar_url: null,
  created_at: '2024-01-15T00:00:00Z',
};

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'tix_001',
    event_id: 'evt_001',
    user_id: 'usr_001',
    ticket_type_id: 'tkt_001',
    status: 'active',
    qr_code: 'ECHO-TIX-001-ABC123',
    nfc_credential: 'nfc_cred_001',
    purchased_at: '2024-02-01T10:30:00Z',
    price_paid: 75,
    holder_name: 'You',
    quantity: 2,
    transfer_deadline_minutes: 30,
    circle: {
      circle_id: 'cir_001',
      role: 'organizer',
      total_slots: 4,
      claimed_slots: 2,
      closes_at: new Date(new Date(getDate(0, 20)).getTime() - 60 * 60 * 1000).toISOString(),
      user_status: 'paid',
      participants: [
        { id: 'usr_001', name: 'You', role: 'organizer', status: 'paid', ticketCount: 2, isCurrentUser: true, avatar_url: 'https://i.pravatar.cc/100?img=12' },
        { id: 'usr_002', name: 'Natasha', role: 'member', status: 'paid', ticketCount: 1, avatar_url: 'https://i.pravatar.cc/100?img=32' },
        { id: 'usr_003', name: 'Steve', role: 'member', status: 'awaiting', ticketCount: 1, avatar_url: 'https://i.pravatar.cc/100?img=18' },
        { id: 'usr_004', name: 'Declined', role: 'member', status: 'declined', ticketCount: 0, avatar_url: null },
      ],
    },
  },
  {
    id: 'tix_002',
    event_id: 'evt_002',
    user_id: 'usr_001',
    ticket_type_id: 'tkt_003',
    status: 'used',
    qr_code: 'ECHO-TIX-002-DEF456',
    nfc_credential: 'nfc_cred_002',
    purchased_at: '2024-02-05T14:00:00Z',
    price_paid: 35,
  },
  {
    id: 'tix_003',
    event_id: 'evt_006',
    user_id: 'usr_001',
    ticket_type_id: 'tkt_009',
    status: 'active',
    qr_code: 'ECHO-TIX-003-GHI789',
    nfc_credential: 'nfc_cred_003',
    purchased_at: '2024-02-07T18:45:00Z',
    price_paid: 125,
    holder_name: 'You',
    quantity: 1,
    transfer_deadline_minutes: 30,
    circle: null,
  },
];

export const mockUser = MOCK_USER;
