/**
 * ECHO Mock Event Generator — 100 Events
 * ════════════════════════════════════════
 * Distribution: 25 music + 20 nightlife + 15 food + 12 art + 10 sports + 8 comedy + 5 tech + 5 wellness
 * Age: 50 all-ages, 25 18+, 25 21+
 * Time: past 30 days → next 60 days
 */

import type { Event, TicketType } from '../types';

// ─── Helpers ─────────────────────────────────────────────────────

const getDate = (daysFromNow: number, hour = 19, minute = 0): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

const endDate = (daysFromNow: number, hour: number, durationHours = 4): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour + durationHours, 0, 0, 0);
  return d.toISOString();
};

const tix = (configs: Array<{ name: string; price: number; avail: number }>, base: string): TicketType[] =>
  configs.map((c, i) => ({ id: `${base}_t${i + 1}`, name: c.name, price: c.price, available: c.avail }));

const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/500`;

// ─── Venue + Host Pools ─────────────────────────────────────────

const VENUES = [
  { name: 'The Warehouse', addr: '123 Industrial Ave, Seattle, WA' },
  { name: 'Botanical Gardens', addr: '456 Park Lane, Seattle, WA' },
  { name: 'Modern Art Museum', addr: '789 Culture Blvd, Seattle, WA' },
  { name: 'Pacific Stadium', addr: '100 Stadium Way, Seattle, WA' },
  { name: 'Emerald Ballroom', addr: '222 Grand Ave, Seattle, WA' },
  { name: 'The Crocodile', addr: '2505 1st Ave, Seattle, WA' },
  { name: 'Neumos', addr: '925 E Pike St, Seattle, WA' },
  { name: 'The Showbox', addr: '1426 1st Ave, Seattle, WA' },
  { name: 'Century Ballroom', addr: '915 E Pine St, Seattle, WA' },
  { name: 'The Neptune Theatre', addr: '1303 NE 45th St, Seattle, WA' },
  { name: 'Gas Works Park', addr: '2101 N Northlake Way, Seattle, WA' },
  { name: 'Pike Place Atrium', addr: '85 Pike St, Seattle, WA' },
  { name: 'Fremont Foundry', addr: '154 N 35th St, Seattle, WA' },
  { name: 'The Paramount Theatre', addr: '911 Pine St, Seattle, WA' },
  { name: 'Benaroya Hall', addr: '200 University St, Seattle, WA' },
  { name: 'Capitol Hill Block', addr: '1600 Broadway, Seattle, WA' },
  { name: 'SoDo Pop-Up', addr: '3801 1st Ave S, Seattle, WA' },
  { name: 'Alki Beach Club', addr: '2700 Alki Ave SW, Seattle, WA' },
  { name: 'Rooftop @ Thompson', addr: '110 Stewart St, Seattle, WA' },
  { name: 'The Cloud Room', addr: '1424 11th Ave, Seattle, WA' },
];

const HOSTS = [
  { name: 'Electric Vibes', verified: true },
  { name: 'Abbe Collective', verified: true },
  { name: 'Culture Club PDX', verified: true },
  { name: 'Night Owl Productions', verified: true },
  { name: 'West Coast Events', verified: true },
  { name: 'Soulful Sounds', verified: true },
  { name: 'Urban Harvest Co.', verified: true },
  { name: 'Laugh Factory NW', verified: false },
  { name: 'Pacific Sports Group', verified: true },
  { name: 'TechConnect Seattle', verified: false },
  { name: 'Zen Wellness', verified: true },
  { name: 'Canvas & Cork', verified: false },
  { name: 'Flavor District', verified: true },
  { name: 'Stadium Live', verified: true },
  { name: 'The Comedy Collective', verified: false },
];

const v = (i: number) => VENUES[i % VENUES.length];
const h = (i: number) => HOSTS[i % HOSTS.length];

// ─── Status Helper ──────────────────────────────────────────────

const statusForDay = (day: number): 'ended' | 'live' | 'on_sale' | 'scheduled' => {
  if (day < -1) return 'ended';
  if (day >= -1 && day <= 0) return 'live';
  return 'on_sale';
};

// ─── EVENTS ─────────────────────────────────────────────────────

const RAW_EVENTS: Event[] = [
  // ════════════════════════════════════════════════════════════════
  // MUSIC — 25 events
  // ════════════════════════════════════════════════════════════════
  { id: 'evt_m01', title: 'Nightfall Festival', description: 'Immersive electronic night with premium visuals and trusted entry.', venue_name: v(0).name, venue_address: v(0).addr, start_time: getDate(0, 20), end_time: endDate(0, 20), category: 'music', image_url: img('nightfall'), ticket_types: tix([{ name: 'GA', price: 75, avail: 250 }, { name: 'VIP', price: 150, avail: 50 }], 'evt_m01'), status: 'live', age_restriction: 21, is_featured: true, host_name: h(0).name, host_verified: h(0).verified },
  { id: 'evt_m02', title: 'Jazz in the Garden', description: 'Smooth jazz outdoors with lounge seating and curated food.', venue_name: v(1).name, venue_address: v(1).addr, start_time: getDate(1, 18), end_time: endDate(1, 18), category: 'music', image_url: img('jazz-garden'), ticket_types: tix([{ name: 'Lawn', price: 35, avail: 500 }, { name: 'Table', price: 120, avail: 20 }], 'evt_m02'), status: 'on_sale', age_restriction: null, host_name: h(1).name, host_verified: true },
  { id: 'evt_m03', title: 'Sunset Rooftop Sessions', description: 'Golden hour DJ sets above the city skyline.', venue_name: v(18).name, venue_address: v(18).addr, start_time: getDate(3, 17), end_time: endDate(3, 17, 5), category: 'music', image_url: img('rooftop-sunset'), ticket_types: tix([{ name: 'GA', price: 45, avail: 150 }], 'evt_m03'), status: 'on_sale', age_restriction: 21, host_name: h(0).name, host_verified: true },
  { id: 'evt_m04', title: 'Indie Rock Revival', description: 'Three bands, one stage, pure raw energy.', venue_name: v(5).name, venue_address: v(5).addr, start_time: getDate(5, 20), end_time: endDate(5, 20), category: 'music', image_url: img('indie-rock'), ticket_types: tix([{ name: 'GA', price: 25, avail: 400 }, { name: 'Backstage', price: 80, avail: 30 }], 'evt_m04'), status: 'on_sale', age_restriction: null, host_name: h(5).name, host_verified: true },
  { id: 'evt_m05', title: 'Symphony Under Stars', description: 'Seattle Symphony performs Beethoven and Dvořák outdoors.', venue_name: v(14).name, venue_address: v(14).addr, start_time: getDate(7, 19, 30), end_time: endDate(7, 19, 3), category: 'music', image_url: img('symphony'), ticket_types: tix([{ name: 'Orchestra', price: 65, avail: 200 }, { name: 'Balcony', price: 40, avail: 300 }], 'evt_m05'), status: 'on_sale', age_restriction: null, host_name: h(1).name, host_verified: true },
  { id: 'evt_m06', title: 'Latin Heat Night', description: 'Salsa, reggaeton, and bachata with live band.', venue_name: v(8).name, venue_address: v(8).addr, start_time: getDate(2, 21), end_time: endDate(2, 21, 5), category: 'music', image_url: img('latin-heat'), ticket_types: tix([{ name: 'GA', price: 30, avail: 300 }], 'evt_m06'), status: 'on_sale', age_restriction: 18, host_name: h(3).name, host_verified: true },
  { id: 'evt_m07', title: 'Acoustic Unplugged', description: 'Intimate singer-songwriter showcase in candlelit venue.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(10, 19), end_time: endDate(10, 19, 3), category: 'music', image_url: img('acoustic'), ticket_types: tix([{ name: 'Seated', price: 40, avail: 80 }], 'evt_m07'), status: 'on_sale', age_restriction: null, host_name: h(5).name, host_verified: true },
  { id: 'evt_m08', title: 'Hip Hop Block Party', description: 'Street-level beats, food trucks, and community energy.', venue_name: v(15).name, venue_address: v(15).addr, start_time: getDate(14, 16), end_time: endDate(14, 16, 6), category: 'music', image_url: img('hiphop-block'), ticket_types: tix([{ name: 'Free Entry', price: 0, avail: 1000 }], 'evt_m08'), status: 'on_sale', age_restriction: null, host_name: h(0).name, host_verified: true },
  { id: 'evt_m09', title: 'Country Roads Festival', description: 'Two-day country music celebration with camping.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(21, 12), end_time: endDate(22, 12, 10), category: 'music', image_url: img('country'), ticket_types: tix([{ name: 'Day Pass', price: 55, avail: 500 }, { name: 'Weekend', price: 120, avail: 200 }, { name: 'VIP Weekend', price: 250, avail: 40 }], 'evt_m09'), status: 'on_sale', age_restriction: null, host_name: h(4).name, host_verified: true },
  { id: 'evt_m10', title: 'Reggae Vibes', description: 'Island rhythms and positive energy all night.', venue_name: v(6).name, venue_address: v(6).addr, start_time: getDate(4, 20), end_time: endDate(4, 20, 5), category: 'music', image_url: img('reggae'), ticket_types: tix([{ name: 'GA', price: 20, avail: 350 }], 'evt_m10'), status: 'on_sale', age_restriction: null, host_name: h(5).name, host_verified: true },
  { id: 'evt_m11', title: 'Piano Noir', description: 'Classical piano meets jazz improvisation in a dark lounge.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(8, 20), end_time: endDate(8, 20, 3), category: 'music', image_url: img('piano-noir'), ticket_types: tix([{ name: 'Lounge', price: 55, avail: 60 }], 'evt_m11'), status: 'on_sale', age_restriction: 21, host_name: h(1).name, host_verified: true },
  { id: 'evt_m12', title: 'EDM Warehouse Rave', description: 'Underground bass music with world-class sound system.', venue_name: v(16).name, venue_address: v(16).addr, start_time: getDate(6, 22), end_time: endDate(7, 0, 6), category: 'music', image_url: img('edm-rave'), ticket_types: tix([{ name: 'GA', price: 40, avail: 600 }, { name: 'VIP', price: 100, avail: 80 }], 'evt_m12'), status: 'on_sale', age_restriction: 18, host_name: h(3).name, host_verified: true },
  { id: 'evt_m13', title: 'Blues & Brews', description: 'Live blues with craft beer pairings.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(12, 17), end_time: endDate(12, 17, 5), category: 'music', image_url: img('blues-brews'), ticket_types: tix([{ name: 'GA', price: 35, avail: 200 }, { name: 'Beer Flight Add-on', price: 55, avail: 100 }], 'evt_m13'), status: 'on_sale', age_restriction: 21, host_name: h(12).name, host_verified: true },
  { id: 'evt_m14', title: 'K-Pop Dance Night', description: 'Cover dance performances and K-pop DJ sets.', venue_name: v(7).name, venue_address: v(7).addr, start_time: getDate(9, 19), end_time: endDate(9, 19, 5), category: 'music', image_url: img('kpop'), ticket_types: tix([{ name: 'GA', price: 25, avail: 450 }], 'evt_m14'), status: 'on_sale', age_restriction: null, host_name: h(0).name, host_verified: true },
  { id: 'evt_m15', title: 'Afrobeats Summer Jam', description: 'Afrobeats, amapiano, and dancehall all night.', venue_name: v(4).name, venue_address: v(4).addr, start_time: getDate(16, 21), end_time: endDate(16, 21, 5), category: 'music', image_url: img('afrobeats'), ticket_types: tix([{ name: 'GA', price: 35, avail: 400 }, { name: 'VIP Table', price: 200, avail: 15 }], 'evt_m15'), status: 'on_sale', age_restriction: 18, host_name: h(3).name, host_verified: true },
  // Past music events
  { id: 'evt_m16', title: 'New Year\'s Eve Gala', description: 'Ring in the new year with live orchestra.', venue_name: v(14).name, venue_address: v(14).addr, start_time: getDate(-28, 21), end_time: endDate(-28, 21, 5), category: 'music', image_url: img('nye-gala'), ticket_types: tix([{ name: 'GA', price: 95, avail: 0 }], 'evt_m16'), status: 'ended', age_restriction: 21, host_name: h(1).name, host_verified: true },
  { id: 'evt_m17', title: 'R&B Slow Jams', description: 'Throwback R&B with live vocalists.', venue_name: v(8).name, venue_address: v(8).addr, start_time: getDate(-14, 20), end_time: endDate(-14, 20, 4), category: 'music', image_url: img('rnb'), ticket_types: tix([{ name: 'GA', price: 30, avail: 0 }], 'evt_m17'), status: 'ended', age_restriction: 18, host_name: h(5).name, host_verified: true },
  { id: 'evt_m18', title: 'Spring Concert Series', description: 'Weekly emerging artist showcase.', venue_name: v(9).name, venue_address: v(9).addr, start_time: getDate(-7, 19), end_time: endDate(-7, 19, 3), category: 'music', image_url: img('spring-concert'), ticket_types: tix([{ name: 'GA', price: 15, avail: 0 }], 'evt_m18'), status: 'ended', age_restriction: null, host_name: h(0).name, host_verified: true },
  { id: 'evt_m19', title: 'Drum Circle Gathering', description: 'Community drum circle on the waterfront.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(25, 16), end_time: endDate(25, 16, 3), category: 'music', image_url: img('drums'), ticket_types: tix([{ name: 'Free Entry', price: 0, avail: 300 }], 'evt_m19'), status: 'on_sale', age_restriction: null, host_name: h(5).name, host_verified: true },
  { id: 'evt_m20', title: 'Metal Mayhem', description: 'Heavy metal double-header with local openers.', venue_name: v(5).name, venue_address: v(5).addr, start_time: getDate(18, 20), end_time: endDate(18, 20, 5), category: 'music', image_url: img('metal'), ticket_types: tix([{ name: 'Pit', price: 30, avail: 200 }, { name: 'Balcony', price: 20, avail: 150 }], 'evt_m20'), status: 'on_sale', age_restriction: null, host_name: h(0).name, host_verified: true },
  { id: 'evt_m21', title: 'Vinyl & Vino', description: 'Rare vinyl listening party with wine pairings.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(30, 19), end_time: endDate(30, 19, 3), category: 'music', image_url: img('vinyl-vino'), ticket_types: tix([{ name: 'Seated', price: 45, avail: 40 }], 'evt_m21'), status: 'on_sale', age_restriction: 21, host_name: h(1).name, host_verified: true },
  { id: 'evt_m22', title: 'Gospel Brunch', description: 'Sunday gospel with soul food brunch buffet.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(11, 11), end_time: endDate(11, 11, 3), category: 'music', image_url: img('gospel'), ticket_types: tix([{ name: 'Brunch + Show', price: 50, avail: 120 }], 'evt_m22'), status: 'on_sale', age_restriction: null, host_name: h(5).name, host_verified: true },
  { id: 'evt_m23', title: 'Techno Therapy', description: 'Deep techno and minimal house until dawn.', venue_name: v(16).name, venue_address: v(16).addr, start_time: getDate(13, 23), end_time: endDate(14, 0, 6), category: 'music', image_url: img('techno'), ticket_types: tix([{ name: 'GA', price: 35, avail: 500 }], 'evt_m23'), status: 'on_sale', age_restriction: 21, host_name: h(3).name, host_verified: true },
  { id: 'evt_m24', title: 'Singer-Songwriter Open Mic', description: 'Open mic night — sign up at the door.', venue_name: v(6).name, venue_address: v(6).addr, start_time: getDate(15, 19), end_time: endDate(15, 19, 3), category: 'music', image_url: img('open-mic'), ticket_types: tix([{ name: 'Free', price: 0, avail: 200 }], 'evt_m24'), status: 'on_sale', age_restriction: null, host_name: h(5).name, host_verified: true },
  { id: 'evt_m25', title: 'Funk & Soul Revival', description: 'Funk classics with a 10-piece live band.', venue_name: v(7).name, venue_address: v(7).addr, start_time: getDate(20, 20), end_time: endDate(20, 20, 4), category: 'music', image_url: img('funk-soul'), ticket_types: tix([{ name: 'GA', price: 30, avail: 350 }, { name: 'VIP', price: 75, avail: 40 }], 'evt_m25'), status: 'on_sale', age_restriction: 18, host_name: h(0).name, host_verified: true },

  // ════════════════════════════════════════════════════════════════
  // NIGHTLIFE — 20 events
  // ════════════════════════════════════════════════════════════════
  { id: 'evt_n01', title: 'Midnight Masquerade', description: 'Upscale masquerade ball with champagne and live DJ.', venue_name: v(4).name, venue_address: v(4).addr, start_time: getDate(2, 22), end_time: endDate(3, 0, 4), category: 'nightlife', image_url: img('masquerade'), ticket_types: tix([{ name: 'GA', price: 60, avail: 300 }, { name: 'VIP Table', price: 250, avail: 20 }], 'evt_n01'), status: 'on_sale', age_restriction: 21, host_name: h(3).name, host_verified: true },
  { id: 'evt_n02', title: 'Neon Nights', description: 'UV paint party with glow-in-the-dark everything.', venue_name: v(0).name, venue_address: v(0).addr, start_time: getDate(4, 22), end_time: endDate(5, 0, 4), category: 'nightlife', image_url: img('neon-nights'), ticket_types: tix([{ name: 'GA', price: 35, avail: 500 }], 'evt_n02'), status: 'on_sale', age_restriction: 18, host_name: h(0).name, host_verified: true },
  { id: 'evt_n03', title: 'Prohibition Lounge', description: 'Speakeasy cocktail experience with secret password entry.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(6, 21), end_time: endDate(7, 0, 4), category: 'nightlife', image_url: img('speakeasy'), ticket_types: tix([{ name: 'Entry + 2 Cocktails', price: 55, avail: 80 }], 'evt_n03'), status: 'on_sale', age_restriction: 21, host_name: h(1).name, host_verified: true },
  { id: 'evt_n04', title: 'Rooftop Disco', description: 'Disco classics 40 floors above the city.', venue_name: v(18).name, venue_address: v(18).addr, start_time: getDate(8, 21), end_time: endDate(9, 0, 4), category: 'nightlife', image_url: img('rooftop-disco'), ticket_types: tix([{ name: 'GA', price: 40, avail: 200 }], 'evt_n04'), status: 'on_sale', age_restriction: 21, host_name: h(3).name, host_verified: true },
  { id: 'evt_n05', title: 'Foam Party', description: 'Summer foam cannon party with tropical drinks.', venue_name: v(17).name, venue_address: v(17).addr, start_time: getDate(15, 14), end_time: endDate(15, 14, 6), category: 'nightlife', image_url: img('foam-party'), ticket_types: tix([{ name: 'GA', price: 25, avail: 600 }], 'evt_n05'), status: 'on_sale', age_restriction: 18, host_name: h(0).name, host_verified: true },
  { id: 'evt_n06', title: 'Drag Brunch Spectacular', description: 'Brunch, mimosas, and stunning drag performances.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(3, 11), end_time: endDate(3, 11, 3), category: 'nightlife', image_url: img('drag-brunch'), ticket_types: tix([{ name: 'Brunch + Show', price: 45, avail: 150 }], 'evt_n06'), status: 'on_sale', age_restriction: 18, host_name: h(3).name, host_verified: true },
  { id: 'evt_n07', title: 'Silent Disco', description: 'Three DJ channels, wireless headphones, choose your vibe.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(10, 20), end_time: endDate(10, 20, 4), category: 'nightlife', image_url: img('silent-disco'), ticket_types: tix([{ name: 'GA', price: 30, avail: 400 }], 'evt_n07'), status: 'on_sale', age_restriction: null, host_name: h(0).name, host_verified: true },
  { id: 'evt_n08', title: 'Karaoke Royale', description: 'Competitive karaoke with prizes and premium sound.', venue_name: v(6).name, venue_address: v(6).addr, start_time: getDate(5, 20), end_time: endDate(5, 20, 4), category: 'nightlife', image_url: img('karaoke'), ticket_types: tix([{ name: 'Entry', price: 15, avail: 200 }], 'evt_n08'), status: 'on_sale', age_restriction: 21, host_name: h(3).name, host_verified: true },
  { id: 'evt_n09', title: 'Pool Party Takeover', description: 'Daytime pool party with DJs and cabanas.', venue_name: v(17).name, venue_address: v(17).addr, start_time: getDate(22, 12), end_time: endDate(22, 12, 8), category: 'nightlife', image_url: img('pool-party'), ticket_types: tix([{ name: 'GA', price: 35, avail: 400 }, { name: 'Cabana', price: 200, avail: 10 }], 'evt_n09'), status: 'on_sale', age_restriction: 21, host_name: h(0).name, host_verified: true },
  { id: 'evt_n10', title: 'Yacht Party', description: 'Sunset cruise with open bar and DJ.', venue_name: 'Seattle Waterfront Pier 66', venue_address: 'Pier 66, Seattle, WA', start_time: getDate(28, 18), end_time: endDate(28, 18, 4), category: 'nightlife', image_url: img('yacht'), ticket_types: tix([{ name: 'Deck', price: 85, avail: 150 }, { name: 'Captain\'s Table', price: 200, avail: 10 }], 'evt_n10'), status: 'on_sale', age_restriction: 21, host_name: h(3).name, host_verified: true },
  // Past nightlife
  { id: 'evt_n11', title: 'Valentine\'s Glow Party', description: 'Valentine\'s themed glow event.', venue_name: v(4).name, venue_address: v(4).addr, start_time: getDate(-21, 21), end_time: endDate(-21, 21, 5), category: 'nightlife', image_url: img('valentines'), ticket_types: tix([{ name: 'Couple', price: 80, avail: 0 }], 'evt_n11'), status: 'ended', age_restriction: 21, host_name: h(3).name, host_verified: true },
  { id: 'evt_n12', title: 'Casino Night Fundraiser', description: 'Blackjack, roulette, and poker for charity.', venue_name: v(4).name, venue_address: v(4).addr, start_time: getDate(-10, 19), end_time: endDate(-10, 19, 5), category: 'nightlife', image_url: img('casino'), ticket_types: tix([{ name: 'GA', price: 50, avail: 0 }], 'evt_n12'), status: 'ended', age_restriction: 21, host_name: h(3).name, host_verified: true },
  { id: 'evt_n13', title: 'Glow Yoga After Dark', description: 'Nighttime yoga with blacklights and chill music.', venue_name: v(8).name, venue_address: v(8).addr, start_time: getDate(35, 20), end_time: endDate(35, 20, 2), category: 'nightlife', image_url: img('glow-yoga'), ticket_types: tix([{ name: 'Mat Spot', price: 25, avail: 60 }], 'evt_n13'), status: 'on_sale', age_restriction: 18, host_name: h(10).name, host_verified: true },
  { id: 'evt_n14', title: 'Salsa Social', description: 'Beginner lesson + open dance floor.', venue_name: v(8).name, venue_address: v(8).addr, start_time: getDate(11, 20), end_time: endDate(11, 20, 4), category: 'nightlife', image_url: img('salsa'), ticket_types: tix([{ name: 'GA', price: 15, avail: 200 }], 'evt_n14'), status: 'on_sale', age_restriction: null, host_name: h(1).name, host_verified: true },
  { id: 'evt_n15', title: 'After Hours Lounge', description: 'Late night cocktails and deep house.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(17, 23), end_time: endDate(18, 0, 4), category: 'nightlife', image_url: img('after-hours'), ticket_types: tix([{ name: 'Entry', price: 20, avail: 100 }], 'evt_n15'), status: 'on_sale', age_restriction: 21, host_name: h(3).name, host_verified: true },
  { id: 'evt_n16', title: 'Throwback Thursday', description: '90s and 2000s hits all night.', venue_name: v(7).name, venue_address: v(7).addr, start_time: getDate(19, 21), end_time: endDate(19, 21, 4), category: 'nightlife', image_url: img('throwback'), ticket_types: tix([{ name: 'GA', price: 20, avail: 350 }], 'evt_n16'), status: 'on_sale', age_restriction: 18, host_name: h(0).name, host_verified: true },
  { id: 'evt_n17', title: 'House Music Sundays', description: 'Deep house and disco edits. Every Sunday.', venue_name: v(6).name, venue_address: v(6).addr, start_time: getDate(24, 16), end_time: endDate(24, 16, 6), category: 'nightlife', image_url: img('house-sundays'), ticket_types: tix([{ name: 'Free', price: 0, avail: 300 }], 'evt_n17'), status: 'on_sale', age_restriction: 21, host_name: h(3).name, host_verified: true },
  { id: 'evt_n18', title: 'Burlesque Revue', description: 'Elegant burlesque with live jazz band.', venue_name: v(4).name, venue_address: v(4).addr, start_time: getDate(33, 20), end_time: endDate(33, 20, 3), category: 'nightlife', image_url: img('burlesque'), ticket_types: tix([{ name: 'GA', price: 40, avail: 200 }, { name: 'Front Row', price: 75, avail: 30 }], 'evt_n18'), status: 'on_sale', age_restriction: 18, host_name: h(3).name, host_verified: true },
  { id: 'evt_n19', title: 'Warehouse Rave: Chapter II', description: 'Underground dance music in converted warehouse.', venue_name: v(16).name, venue_address: v(16).addr, start_time: getDate(40, 22), end_time: endDate(41, 0, 6), category: 'nightlife', image_url: img('warehouse-2'), ticket_types: tix([{ name: 'Early Bird', price: 25, avail: 200 }, { name: 'GA', price: 40, avail: 400 }], 'evt_n19'), status: 'on_sale', age_restriction: 18, host_name: h(0).name, host_verified: true },
  { id: 'evt_n20', title: 'Champagne & Caviar Soirée', description: 'Black-tie evening with premium champagne tasting.', venue_name: v(4).name, venue_address: v(4).addr, start_time: getDate(45, 19), end_time: endDate(45, 19, 4), category: 'nightlife', image_url: img('champagne'), ticket_types: tix([{ name: 'GA', price: 120, avail: 100 }, { name: 'Platinum', price: 300, avail: 20 }], 'evt_n20'), status: 'on_sale', age_restriction: 21, host_name: h(1).name, host_verified: true },

  // ════════════════════════════════════════════════════════════════
  // FOOD — 15 events
  // ════════════════════════════════════════════════════════════════
  { id: 'evt_f01', title: 'Night Market', description: 'Asian street food vendors under string lights.', venue_name: v(11).name, venue_address: v(11).addr, start_time: getDate(1, 17), end_time: endDate(1, 17, 5), category: 'food', image_url: img('night-market'), ticket_types: tix([{ name: 'Entry', price: 10, avail: 800 }], 'evt_f01'), status: 'on_sale', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f02', title: 'Taco Festival', description: '30+ taco vendors competing for Best Taco title.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(7, 11), end_time: endDate(7, 11, 7), category: 'food', image_url: img('taco-fest'), ticket_types: tix([{ name: 'GA', price: 15, avail: 1000 }, { name: 'VIP Taste Pass', price: 50, avail: 100 }], 'evt_f02'), status: 'on_sale', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f03', title: 'Wine & Cheese Pairing', description: 'Sommelier-led tasting with artisan cheeses.', venue_name: v(11).name, venue_address: v(11).addr, start_time: getDate(9, 18), end_time: endDate(9, 18, 3), category: 'food', image_url: img('wine-cheese'), ticket_types: tix([{ name: 'Tasting', price: 65, avail: 50 }], 'evt_f03'), status: 'on_sale', age_restriction: 21, host_name: h(12).name, host_verified: true },
  { id: 'evt_f04', title: 'Ramen Pop-Up', description: 'Tokyo-style ramen from guest chef.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(3, 17), end_time: endDate(3, 17, 4), category: 'food', image_url: img('ramen'), ticket_types: tix([{ name: 'Seating', price: 35, avail: 60 }], 'evt_f04'), status: 'on_sale', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f05', title: 'BBQ Championship', description: 'Competitive BBQ with live music and cold beer.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(14, 12), end_time: endDate(14, 12, 8), category: 'food', image_url: img('bbq'), ticket_types: tix([{ name: 'GA', price: 20, avail: 500 }, { name: 'Pitmaster VIP', price: 75, avail: 50 }], 'evt_f05'), status: 'on_sale', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f06', title: 'Pasta Making Class', description: 'Hands-on pasta from scratch with Italian chef.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(6, 18), end_time: endDate(6, 18, 3), category: 'food', image_url: img('pasta'), ticket_types: tix([{ name: 'Workshop', price: 80, avail: 20 }], 'evt_f06'), status: 'on_sale', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f07', title: 'Whiskey Tasting Experience', description: 'Single malt flight with expert guidance.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(12, 19), end_time: endDate(12, 19, 2), category: 'food', image_url: img('whiskey'), ticket_types: tix([{ name: 'Tasting', price: 55, avail: 40 }], 'evt_f07'), status: 'on_sale', age_restriction: 21, host_name: h(12).name, host_verified: true },
  { id: 'evt_f08', title: 'Vegan Street Fair', description: 'Plant-based vendors and cooking demos.', venue_name: v(15).name, venue_address: v(15).addr, start_time: getDate(17, 11), end_time: endDate(17, 11, 6), category: 'food', image_url: img('vegan'), ticket_types: tix([{ name: 'Free', price: 0, avail: 600 }], 'evt_f08'), status: 'on_sale', age_restriction: null, host_name: h(6).name, host_verified: true },
  { id: 'evt_f09', title: 'Seafood Fest', description: 'PNW oysters, crab, and salmon celebration.', venue_name: v(17).name, venue_address: v(17).addr, start_time: getDate(21, 12), end_time: endDate(21, 12, 7), category: 'food', image_url: img('seafood'), ticket_types: tix([{ name: 'GA', price: 25, avail: 400 }], 'evt_f09'), status: 'on_sale', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f10', title: 'Chocolate & Wine Gala', description: 'Artisan chocolate paired with Pacific NW wines.', venue_name: v(4).name, venue_address: v(4).addr, start_time: getDate(26, 19), end_time: endDate(26, 19, 3), category: 'food', image_url: img('chocolate-wine'), ticket_types: tix([{ name: 'Tasting', price: 75, avail: 80 }], 'evt_f10'), status: 'on_sale', age_restriction: 21, host_name: h(12).name, host_verified: true },
  // Past food
  { id: 'evt_f11', title: 'Dumpling Festival', description: 'Asian dumpling competition.', venue_name: v(11).name, venue_address: v(11).addr, start_time: getDate(-18, 11), end_time: endDate(-18, 11, 6), category: 'food', image_url: img('dumplings'), ticket_types: tix([{ name: 'GA', price: 12, avail: 0 }], 'evt_f11'), status: 'ended', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f12', title: 'Coffee Expo', description: 'Specialty coffee roasters and latte art.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(-5, 9), end_time: endDate(-5, 9, 8), category: 'food', image_url: img('coffee'), ticket_types: tix([{ name: 'GA', price: 20, avail: 0 }], 'evt_f12'), status: 'ended', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f13', title: 'Brunch Battle', description: 'Chefs compete for best brunch dish.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(32, 10), end_time: endDate(32, 10, 4), category: 'food', image_url: img('brunch'), ticket_types: tix([{ name: 'GA + Tasting', price: 40, avail: 200 }], 'evt_f13'), status: 'on_sale', age_restriction: null, host_name: h(12).name, host_verified: true },
  { id: 'evt_f14', title: 'Craft Beer Festival', description: '40+ local breweries pouring their finest.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(38, 14), end_time: endDate(38, 14, 6), category: 'food', image_url: img('beer-fest'), ticket_types: tix([{ name: 'GA', price: 30, avail: 600 }, { name: 'VIP Early', price: 60, avail: 100 }], 'evt_f14'), status: 'on_sale', age_restriction: 21, host_name: h(12).name, host_verified: true },
  { id: 'evt_f15', title: 'Sushi Masterclass', description: 'Learn to roll with a master sushi chef.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(50, 18), end_time: endDate(50, 18, 2), category: 'food', image_url: img('sushi'), ticket_types: tix([{ name: 'Class', price: 95, avail: 16 }], 'evt_f15'), status: 'on_sale', age_restriction: null, host_name: h(12).name, host_verified: true },

  // ════════════════════════════════════════════════════════════════
  // ART — 12 events
  // ════════════════════════════════════════════════════════════════
  { id: 'evt_a01', title: 'Art & Soul Exhibition', description: 'Contemporary gallery with timed access.', venue_name: v(2).name, venue_address: v(2).addr, start_time: getDate(1, 10), end_time: endDate(1, 10, 10), category: 'art', image_url: img('art-soul'), ticket_types: tix([{ name: 'Timed Entry', price: 18, avail: 300 }], 'evt_a01'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a02', title: 'Mural Walk', description: 'Guided tour of Capitol Hill street art.', venue_name: v(15).name, venue_address: v(15).addr, start_time: getDate(5, 14), end_time: endDate(5, 14, 2), category: 'art', image_url: img('mural'), ticket_types: tix([{ name: 'Tour', price: 12, avail: 30 }], 'evt_a02'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a03', title: 'Pottery Workshop', description: 'Wheel-throwing class for beginners.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(8, 13), end_time: endDate(8, 13, 3), category: 'art', image_url: img('pottery'), ticket_types: tix([{ name: 'Workshop', price: 45, avail: 12 }], 'evt_a03'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a04', title: 'Photography Night', description: 'Photo walk and critique with pro photographer.', venue_name: v(11).name, venue_address: v(11).addr, start_time: getDate(10, 18), end_time: endDate(10, 18, 3), category: 'art', image_url: img('photo-walk'), ticket_types: tix([{ name: 'Walk + Critique', price: 25, avail: 20 }], 'evt_a04'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a05', title: 'Digital Art Showcase', description: 'Projection art and interactive installations.', venue_name: v(2).name, venue_address: v(2).addr, start_time: getDate(15, 18), end_time: endDate(15, 18, 4), category: 'art', image_url: img('digital-art'), ticket_types: tix([{ name: 'GA', price: 22, avail: 250 }], 'evt_a05'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a06', title: 'Paint & Sip', description: 'Painting class with wine — no experience needed.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(4, 18), end_time: endDate(4, 18, 3), category: 'art', image_url: img('paint-sip'), ticket_types: tix([{ name: 'Canvas + Wine', price: 40, avail: 30 }], 'evt_a06'), status: 'on_sale', age_restriction: 21, host_name: h(11).name, host_verified: false },
  { id: 'evt_a07', title: 'Sculpture Garden Opening', description: 'New outdoor sculpture exhibition opening night.', venue_name: v(1).name, venue_address: v(1).addr, start_time: getDate(20, 17), end_time: endDate(20, 17, 3), category: 'art', image_url: img('sculpture'), ticket_types: tix([{ name: 'Free', price: 0, avail: 500 }], 'evt_a07'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a08', title: 'Watercolor Workshop', description: 'Landscape watercolors with local artist.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(25, 10), end_time: endDate(25, 10, 3), category: 'art', image_url: img('watercolor'), ticket_types: tix([{ name: 'Class', price: 35, avail: 15 }], 'evt_a08'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  // Past art
  { id: 'evt_a09', title: 'Graffiti Jam', description: 'Live graffiti art with DJs.', venue_name: v(16).name, venue_address: v(16).addr, start_time: getDate(-12, 14), end_time: endDate(-12, 14, 5), category: 'art', image_url: img('graffiti'), ticket_types: tix([{ name: 'Free', price: 0, avail: 0 }], 'evt_a09'), status: 'ended', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a10', title: 'Glass Blowing Demo', description: 'Watch master glassblower create live.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(30, 11), end_time: endDate(30, 11, 3), category: 'art', image_url: img('glass'), ticket_types: tix([{ name: 'Viewing', price: 15, avail: 40 }], 'evt_a10'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a11', title: 'Zine Fair', description: 'Independent publishers and zine makers.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(35, 11), end_time: endDate(35, 11, 6), category: 'art', image_url: img('zine'), ticket_types: tix([{ name: 'Free', price: 0, avail: 300 }], 'evt_a11'), status: 'on_sale', age_restriction: null, host_name: h(11).name, host_verified: false },
  { id: 'evt_a12', title: 'Life Drawing Session', description: 'Drop-in figure drawing with live model.', venue_name: v(2).name, venue_address: v(2).addr, start_time: getDate(42, 18), end_time: endDate(42, 18, 3), category: 'art', image_url: img('life-draw'), ticket_types: tix([{ name: 'Drop-in', price: 20, avail: 25 }], 'evt_a12'), status: 'on_sale', age_restriction: 18, host_name: h(11).name, host_verified: false },

  // ════════════════════════════════════════════════════════════════
  // SPORTS — 10 events
  // ════════════════════════════════════════════════════════════════
  { id: 'evt_s01', title: '5K Glow Run', description: 'Night run with glow gear and after-party.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(6, 19), end_time: endDate(6, 19, 3), category: 'sports', image_url: img('glow-run'), ticket_types: tix([{ name: 'Runner', price: 35, avail: 500 }], 'evt_s01'), status: 'on_sale', age_restriction: null, host_name: h(8).name, host_verified: true },
  { id: 'evt_s02', title: 'Pickup Basketball Tournament', description: '3-on-3 double elimination bracket.', venue_name: v(3).name, venue_address: v(3).addr, start_time: getDate(9, 10), end_time: endDate(9, 10, 8), category: 'sports', image_url: img('basketball'), ticket_types: tix([{ name: 'Team Entry', price: 60, avail: 32 }, { name: 'Spectator', price: 10, avail: 200 }], 'evt_s02'), status: 'on_sale', age_restriction: null, host_name: h(8).name, host_verified: true },
  { id: 'evt_s03', title: 'Boxing Night', description: 'Amateur boxing card with 8 bouts.', venue_name: v(0).name, venue_address: v(0).addr, start_time: getDate(13, 19), end_time: endDate(13, 19, 4), category: 'sports', image_url: img('boxing'), ticket_types: tix([{ name: 'GA', price: 40, avail: 300 }, { name: 'Ringside', price: 100, avail: 40 }], 'evt_s03'), status: 'on_sale', age_restriction: 18, host_name: h(13).name, host_verified: true },
  { id: 'evt_s04', title: 'Yoga in the Park', description: 'Free community yoga every Saturday.', venue_name: v(1).name, venue_address: v(1).addr, start_time: getDate(2, 9), end_time: endDate(2, 9, 1), category: 'sports', image_url: img('yoga-park'), ticket_types: tix([{ name: 'Free', price: 0, avail: 200 }], 'evt_s04'), status: 'on_sale', age_restriction: null, host_name: h(10).name, host_verified: true },
  { id: 'evt_s05', title: 'Kickball League Opener', description: 'Adult kickball league opening night.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(16, 18), end_time: endDate(16, 18, 3), category: 'sports', image_url: img('kickball'), ticket_types: tix([{ name: 'Player', price: 25, avail: 100 }], 'evt_s05'), status: 'on_sale', age_restriction: 18, host_name: h(8).name, host_verified: true },
  { id: 'evt_s06', title: 'Volleyball Beach Day', description: 'Beach volleyball tournament + BBQ.', venue_name: v(17).name, venue_address: v(17).addr, start_time: getDate(23, 10), end_time: endDate(23, 10, 8), category: 'sports', image_url: img('volleyball'), ticket_types: tix([{ name: 'Team', price: 40, avail: 24 }, { name: 'Spectator', price: 0, avail: 200 }], 'evt_s06'), status: 'on_sale', age_restriction: null, host_name: h(8).name, host_verified: true },
  { id: 'evt_s07', title: 'Marathon Training Run', description: 'Group training for Seattle Marathon.', venue_name: v(10).name, venue_address: v(10).addr, start_time: getDate(29, 7), end_time: endDate(29, 7, 3), category: 'sports', image_url: img('marathon'), ticket_types: tix([{ name: 'Free', price: 0, avail: 300 }], 'evt_s07'), status: 'on_sale', age_restriction: null, host_name: h(8).name, host_verified: true },
  // Past sports
  { id: 'evt_s08', title: 'Spartan Race', description: 'Obstacle course race.', venue_name: v(3).name, venue_address: v(3).addr, start_time: getDate(-20, 8), end_time: endDate(-20, 8, 6), category: 'sports', image_url: img('spartan'), ticket_types: tix([{ name: 'Runner', price: 75, avail: 0 }], 'evt_s08'), status: 'ended', age_restriction: 18, host_name: h(8).name, host_verified: true },
  { id: 'evt_s09', title: 'Dodgeball Tournament', description: 'Adults-only dodgeball with prizes.', venue_name: v(3).name, venue_address: v(3).addr, start_time: getDate(40, 14), end_time: endDate(40, 14, 4), category: 'sports', image_url: img('dodgeball'), ticket_types: tix([{ name: 'Team', price: 50, avail: 16 }], 'evt_s09'), status: 'on_sale', age_restriction: 18, host_name: h(8).name, host_verified: true },
  { id: 'evt_s10', title: 'Rock Climbing Social', description: 'Indoor climbing gym meetup for all levels.', venue_name: 'Seattle Bouldering Project', venue_address: '900 Poplar Pl S, Seattle, WA', start_time: getDate(36, 18), end_time: endDate(36, 18, 3), category: 'sports', image_url: img('climbing'), ticket_types: tix([{ name: 'Entry + Gear', price: 20, avail: 50 }], 'evt_s10'), status: 'on_sale', age_restriction: null, host_name: h(8).name, host_verified: true },

  // ════════════════════════════════════════════════════════════════
  // COMEDY — 8 events
  // ════════════════════════════════════════════════════════════════
  { id: 'evt_c01', title: 'Stand-Up Showcase', description: 'Five comedians, one stage, no filter.', venue_name: v(9).name, venue_address: v(9).addr, start_time: getDate(3, 20), end_time: endDate(3, 20, 2), category: 'comedy', image_url: img('standup'), ticket_types: tix([{ name: 'GA', price: 20, avail: 200 }], 'evt_c01'), status: 'on_sale', age_restriction: 18, host_name: h(14).name, host_verified: false },
  { id: 'evt_c02', title: 'Improv Night', description: 'Unscripted comedy with audience suggestions.', venue_name: v(9).name, venue_address: v(9).addr, start_time: getDate(7, 20), end_time: endDate(7, 20, 2), category: 'comedy', image_url: img('improv'), ticket_types: tix([{ name: 'GA', price: 15, avail: 150 }], 'evt_c02'), status: 'on_sale', age_restriction: null, host_name: h(14).name, host_verified: false },
  { id: 'evt_c03', title: 'Roast Battle', description: 'Comedians roast each other — audience votes.', venue_name: v(6).name, venue_address: v(6).addr, start_time: getDate(11, 21), end_time: endDate(11, 21, 2), category: 'comedy', image_url: img('roast'), ticket_types: tix([{ name: 'GA', price: 18, avail: 200 }], 'evt_c03'), status: 'on_sale', age_restriction: 18, host_name: h(14).name, host_verified: false },
  { id: 'evt_c04', title: 'Open Mic Comedy', description: 'Try your five minutes — sign up at door.', venue_name: v(6).name, venue_address: v(6).addr, start_time: getDate(5, 19), end_time: endDate(5, 19, 3), category: 'comedy', image_url: img('open-mic-comedy'), ticket_types: tix([{ name: 'Free', price: 0, avail: 100 }], 'evt_c04'), status: 'on_sale', age_restriction: null, host_name: h(7).name, host_verified: false },
  { id: 'evt_c05', title: 'Comedy & Cocktails', description: 'Headliner set with craft cocktail menu.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(18, 20), end_time: endDate(18, 20, 2), category: 'comedy', image_url: img('comedy-cocktails'), ticket_types: tix([{ name: 'GA', price: 25, avail: 80 }], 'evt_c05'), status: 'on_sale', age_restriction: 21, host_name: h(14).name, host_verified: false },
  { id: 'evt_c06', title: 'Sketch Comedy Review', description: 'Original sketch comedy from local troupe.', venue_name: v(9).name, venue_address: v(9).addr, start_time: getDate(25, 19), end_time: endDate(25, 19, 2), category: 'comedy', image_url: img('sketch'), ticket_types: tix([{ name: 'GA', price: 15, avail: 200 }], 'evt_c06'), status: 'on_sale', age_restriction: null, host_name: h(14).name, host_verified: false },
  // Past comedy
  { id: 'evt_c07', title: 'New Year Comedy Bash', description: 'NYE comedy and champagne toast.', venue_name: v(9).name, venue_address: v(9).addr, start_time: getDate(-25, 20), end_time: endDate(-25, 20, 3), category: 'comedy', image_url: img('nye-comedy'), ticket_types: tix([{ name: 'GA', price: 35, avail: 0 }], 'evt_c07'), status: 'ended', age_restriction: 21, host_name: h(14).name, host_verified: false },
  { id: 'evt_c08', title: 'Dark Humor Night', description: 'Nothing is off limits. You\'ve been warned.', venue_name: v(6).name, venue_address: v(6).addr, start_time: getDate(48, 21), end_time: endDate(48, 21, 2), category: 'comedy', image_url: img('dark-humor'), ticket_types: tix([{ name: 'GA', price: 20, avail: 150 }], 'evt_c08'), status: 'on_sale', age_restriction: 18, host_name: h(7).name, host_verified: false },

  // ════════════════════════════════════════════════════════════════
  // TECH — 5 events
  // ════════════════════════════════════════════════════════════════
  { id: 'evt_t01', title: 'AI & Design Summit', description: 'How AI is reshaping product design.', venue_name: v(2).name, venue_address: v(2).addr, start_time: getDate(12, 9), end_time: endDate(12, 9, 8), category: 'tech', image_url: img('ai-summit'), ticket_types: tix([{ name: 'GA', price: 50, avail: 300 }, { name: 'Workshop Pass', price: 150, avail: 50 }], 'evt_t01'), status: 'on_sale', age_restriction: null, host_name: h(9).name, host_verified: false },
  { id: 'evt_t02', title: 'Startup Demo Day', description: '12 startups pitch to investors and public.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(19, 14), end_time: endDate(19, 14, 4), category: 'tech', image_url: img('demo-day'), ticket_types: tix([{ name: 'Free', price: 0, avail: 200 }], 'evt_t02'), status: 'on_sale', age_restriction: null, host_name: h(9).name, host_verified: false },
  { id: 'evt_t03', title: 'Hackathon Weekend', description: '48-hour build sprint with prizes.', venue_name: v(12).name, venue_address: v(12).addr, start_time: getDate(27, 18), end_time: endDate(29, 18, 0), category: 'tech', image_url: img('hackathon'), ticket_types: tix([{ name: 'Hacker', price: 25, avail: 100 }], 'evt_t03'), status: 'on_sale', age_restriction: null, host_name: h(9).name, host_verified: false },
  { id: 'evt_t04', title: 'Web3 Meetup', description: 'Blockchain builders sharing progress.', venue_name: v(19).name, venue_address: v(19).addr, start_time: getDate(8, 18), end_time: endDate(8, 18, 3), category: 'tech', image_url: img('web3'), ticket_types: tix([{ name: 'Free', price: 0, avail: 80 }], 'evt_t04'), status: 'on_sale', age_restriction: null, host_name: h(9).name, host_verified: false },
  // Past tech
  { id: 'evt_t05', title: 'Product Design Week', description: 'Week-long design conference.', venue_name: v(2).name, venue_address: v(2).addr, start_time: getDate(-15, 9), end_time: endDate(-11, 17, 0), category: 'tech', image_url: img('design-week'), ticket_types: tix([{ name: 'Full Pass', price: 200, avail: 0 }], 'evt_t05'), status: 'ended', age_restriction: null, host_name: h(9).name, host_verified: false },

  // ════════════════════════════════════════════════════════════════
  // WELLNESS — 5 events
  // ════════════════════════════════════════════════════════════════
  { id: 'evt_w01', title: 'Sound Bath Meditation', description: 'Crystal singing bowls and guided meditation.', venue_name: v(1).name, venue_address: v(1).addr, start_time: getDate(4, 10), end_time: endDate(4, 10, 2), category: 'wellness', image_url: img('sound-bath'), ticket_types: tix([{ name: 'Mat Spot', price: 30, avail: 40 }], 'evt_w01'), status: 'on_sale', age_restriction: null, host_name: h(10).name, host_verified: true },
  { id: 'evt_w02', title: 'Breathwork Circle', description: 'Guided breathwork and cold plunge.', venue_name: v(17).name, venue_address: v(17).addr, start_time: getDate(10, 8), end_time: endDate(10, 8, 2), category: 'wellness', image_url: img('breathwork'), ticket_types: tix([{ name: 'Session', price: 25, avail: 30 }], 'evt_w02'), status: 'on_sale', age_restriction: null, host_name: h(10).name, host_verified: true },
  { id: 'evt_w03', title: 'Forest Bathing Walk', description: 'Guided mindful walk through old growth forest.', venue_name: 'Discovery Park', venue_address: '3801 Discovery Park Blvd, Seattle, WA', start_time: getDate(14, 9), end_time: endDate(14, 9, 3), category: 'wellness', image_url: img('forest'), ticket_types: tix([{ name: 'Walk', price: 15, avail: 20 }], 'evt_w03'), status: 'on_sale', age_restriction: null, host_name: h(10).name, host_verified: true },
  { id: 'evt_w04', title: 'Wellness Retreat Day', description: 'Full-day retreat with yoga, meditation, and plant-based lunch.', venue_name: v(1).name, venue_address: v(1).addr, start_time: getDate(22, 8), end_time: endDate(22, 8, 10), category: 'wellness', image_url: img('retreat'), ticket_types: tix([{ name: 'Full Day', price: 85, avail: 30 }], 'evt_w04'), status: 'on_sale', age_restriction: null, host_name: h(10).name, host_verified: true },
  { id: 'evt_w05', title: 'Moonlight Meditation', description: 'Full moon meditation on the waterfront.', venue_name: v(17).name, venue_address: v(17).addr, start_time: getDate(34, 20), end_time: endDate(34, 20, 2), category: 'wellness', image_url: img('moonlight'), ticket_types: tix([{ name: 'Free', price: 0, avail: 100 }], 'evt_w05'), status: 'on_sale', age_restriction: null, host_name: h(10).name, host_verified: true },
];

export const GENERATED_EVENTS: Event[] = RAW_EVENTS.map((event) => ({
  // Apply default locked event policies based on event characteristics
  allow_refunds: event.ticket_types.every(t => t.price === 0) ? true   // Free events: always refundable
    : event.age_restriction === 21 ? false                             // 21+ events: no refunds (strict)
    : true,                                                            // Default: refunds allowed
  allow_transfers: event.status === 'ended' ? false                    // Past events: no transfers
    : true,                                                            // Default: transfers allowed
  ...event,                                                            // Event-level overrides win
}));
