import type { Event } from '../types';
import type { HostEventRuntime } from './doorModeService';
import type { CloseoutReport } from './eventCloseoutReportService';

export const ECHO_DEMO_HOST_NAME = 'Demo User';
export const ECHO_DEMO_HOST_EVENT_PREFIX = 'evt_demo_host_';

const getDate = (daysFromNow: number, hour: number, minute = 0) => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

const getRelativeDate = (minutesFromNow: number) => new Date(Date.now() + minutesFromNow * 60 * 1000).toISOString();

const ticketTypes = (eventId: string, tiers: Array<{ name: string; price: number; capacity: number }>) =>
  tiers.map((tier, index) => ({
    id: `${eventId}_tier_${index + 1}`,
    name: tier.name,
    price: tier.price,
    available: tier.capacity,
  }));

export const MOCK_HOST_EVENTS: Event[] = [
  {
    id: 'evt_demo_host_live_001',
    title: 'ECHO Live: Midnight Pulse',
    description: 'A live 21+ nightlife event seeded for Door Mode scans, live check-in, social promotion, wallet discovery, and host analytics testing.',
    venue_id: 'venue_demo_nova_rooftop',
    venue_name: 'Nova Rooftop',
    venue_address: '1201 First Ave, Seattle, WA',
    start_time: getRelativeDate(-45),
    end_time: getRelativeDate(180),
    category: 'music',
    image_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30',
    ticket_types: ticketTypes('evt_demo_host_live_001', [
      { name: 'General Admission', price: 35, capacity: 180 },
      { name: 'VIP Access', price: 85, capacity: 40 },
    ]),
    status: 'live',
    age_restriction: 21,
    allow_refunds: false,
    allow_transfers: true,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
    is_featured: true,
  },
  {
    id: 'evt_demo_host_ready_002',
    title: 'Golden Hour Mixer',
    description: 'Starts inside the two-hour Door Mode window so hosts can test entry readiness, passcode preflight, and locked/unlocked door states.',
    venue_id: 'venue_demo_tacoma_social',
    venue_name: 'Tacoma Social Hall',
    venue_address: '742 Pacific Ave, Tacoma, WA',
    start_time: getRelativeDate(90),
    end_time: getRelativeDate(330),
    category: 'social',
    image_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622',
    ticket_types: ticketTypes('evt_demo_host_ready_002', [
      { name: 'Early Entry', price: 20, capacity: 60 },
      { name: 'General Admission', price: 30, capacity: 100 },
    ]),
    status: 'on_sale',
    age_restriction: 18,
    allow_refunds: true,
    allow_transfers: true,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
  },
  {
    id: 'evt_demo_host_locked_003',
    title: 'Capitol Hill Afrobeats Lounge',
    description: 'Starts more than two hours from now so hosts can verify Door Mode remains intentionally inaccessible until it is operationally needed.',
    venue_id: 'venue_demo_midnight_loft',
    venue_name: 'Midnight Loft',
    venue_address: '915 E Pine St, Seattle, WA',
    start_time: getRelativeDate(390),
    end_time: getRelativeDate(690),
    category: 'music',
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a',
    ticket_types: ticketTypes('evt_demo_host_locked_003', [
      { name: 'General Admission', price: 28, capacity: 180 },
      { name: 'Table Hold', price: 120, capacity: 20 },
    ]),
    status: 'on_sale',
    age_restriction: 21,
    allow_refunds: false,
    allow_transfers: true,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
  },
  {
    id: 'evt_demo_host_nonprofit_004',
    title: 'Golden Futures Scholarship Night',
    description: 'A nonprofit-focused event for testing donation-friendly positioning, fee transparency, report exports, and community impact language.',
    venue_id: 'venue_demo_civic_center',
    venue_name: 'Tacoma Civic Center',
    venue_address: '1500 Commerce St, Tacoma, WA',
    start_time: getDate(1, 18, 30),
    end_time: getDate(1, 22, 0),
    category: 'nonprofit',
    image_url: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6',
    ticket_types: ticketTypes('evt_demo_host_nonprofit_004', [
      { name: 'Community Entry', price: 0, capacity: 100 },
      { name: 'Supporter Ticket', price: 50, capacity: 80 },
      { name: 'Sponsor Table', price: 250, capacity: 20 },
    ]),
    status: 'on_sale',
    age_restriction: null,
    allow_refunds: true,
    allow_transfers: true,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
    is_featured: true,
  },
  {
    id: 'evt_demo_host_circle_005',
    title: 'R&B Dinner Party',
    description: 'A polished social event for testing ECHO Circle prompts, grouped tickets, invite language, wallet priority, and promotion copy.',
    venue_id: 'venue_demo_listening_room',
    venue_name: 'The Listening Room',
    venue_address: '88 Western Ave, Seattle, WA',
    start_time: getDate(2, 20, 0),
    end_time: getDate(3, 0, 30),
    category: 'music',
    image_url: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b',
    ticket_types: ticketTypes('evt_demo_host_circle_005', [
      { name: 'Dinner + Entry', price: 65, capacity: 120 },
      { name: 'Circle Table', price: 95, capacity: 40 },
    ]),
    status: 'on_sale',
    age_restriction: 21,
    allow_refunds: false,
    allow_transfers: true,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
  },
  {
    id: 'evt_demo_host_soldout_006',
    title: 'Skyline VIP Tasting',
    description: 'A high-demand near-sellout event for testing urgency, sold-through analytics, payout projections, and waitlist-ready promotion posture.',
    venue_id: 'venue_demo_skyline_room',
    venue_name: 'Skyline Room',
    venue_address: '400 Broad St, Seattle, WA',
    start_time: getDate(3, 19, 0),
    end_time: getDate(3, 23, 0),
    category: 'food',
    image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
    ticket_types: ticketTypes('evt_demo_host_soldout_006', [
      { name: 'Tasting Pass', price: 95, capacity: 70 },
      { name: 'VIP Pairing', price: 175, capacity: 30 },
    ]),
    status: 'on_sale',
    age_restriction: 21,
    allow_refunds: false,
    allow_transfers: false,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
  },
  {
    id: 'evt_demo_host_lowsales_007',
    title: 'Community Arts Market',
    description: 'A lower-velocity event for testing AI promotion recommendations, market pulse opportunities, and host action prompts.',
    venue_id: 'venue_demo_arts_center',
    venue_name: 'Pierce County Arts Center',
    venue_address: '930 Broadway, Tacoma, WA',
    start_time: getDate(4, 13, 0),
    end_time: getDate(4, 18, 0),
    category: 'art',
    image_url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b',
    ticket_types: ticketTypes('evt_demo_host_lowsales_007', [
      { name: 'Market Entry', price: 12, capacity: 220 },
      { name: 'Workshop Add-on', price: 35, capacity: 40 },
    ]),
    status: 'on_sale',
    age_restriction: null,
    allow_refunds: true,
    allow_transfers: true,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
  },
  {
    id: 'evt_demo_host_conference_008',
    title: 'Access Tech Forum',
    description: 'A professional event for testing tiered tickets, host dashboard finance rows, event discovery, and enterprise-style promotion copy.',
    venue_id: 'venue_demo_convention_center',
    venue_name: 'Seattle Convention Center',
    venue_address: '705 Pike St, Seattle, WA',
    start_time: getDate(6, 9, 0),
    end_time: getDate(6, 17, 30),
    category: 'tech',
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87',
    ticket_types: ticketTypes('evt_demo_host_conference_008', [
      { name: 'Day Pass', price: 149, capacity: 260 },
      { name: 'Founder Pass', price: 399, capacity: 40 },
    ]),
    status: 'on_sale',
    age_restriction: null,
    allow_refunds: true,
    allow_transfers: true,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
  },
  {
    id: 'evt_demo_host_past_report_009',
    title: 'Completed: Jazz Garden Social',
    description: 'A completed event with seeded real closeout data for testing Closeout Report labels, downloads, attendance metrics, and report state.',
    venue_id: 'venue_demo_botanical_garden',
    venue_name: 'Botanical Garden Pavilion',
    venue_address: '2300 Arboretum Dr E, Seattle, WA',
    start_time: getDate(-7, 18, 0),
    end_time: getDate(-7, 22, 0),
    category: 'music',
    image_url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629',
    ticket_types: ticketTypes('evt_demo_host_past_report_009', [
      { name: 'Garden Entry', price: 35, capacity: 160 },
      { name: 'Reserved Table', price: 120, capacity: 24 },
    ]),
    status: 'ended',
    age_restriction: null,
    allow_refunds: false,
    allow_transfers: false,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
  },
  {
    id: 'evt_demo_host_past_preview_010',
    title: 'Completed: Volunteer Appreciation Night',
    description: 'A completed event without a seeded closeout report so hosts can test the Report Preview fallback and download pill behavior.',
    venue_id: 'venue_demo_waterfront_hall',
    venue_name: 'Waterfront Hall',
    venue_address: '1101 Dock St, Tacoma, WA',
    start_time: getDate(-14, 17, 30),
    end_time: getDate(-14, 21, 30),
    category: 'nonprofit',
    image_url: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1',
    ticket_types: ticketTypes('evt_demo_host_past_preview_010', [
      { name: 'General Entry', price: 0, capacity: 140 },
      { name: 'Donation Supporter', price: 25, capacity: 60 },
    ]),
    status: 'ended',
    age_restriction: null,
    allow_refunds: false,
    allow_transfers: false,
    host_name: ECHO_DEMO_HOST_NAME,
    host_verified: true,
  },
];

export const MOCK_HOST_EVENT_RUNTIME: Record<string, Omit<HostEventRuntime, 'updatedAt'>> = {
  evt_demo_host_live_001: { eventId: 'evt_demo_host_live_001', sold: 184, checkedIn: 76, revenue: 8420, status: 'live' },
  evt_demo_host_ready_002: { eventId: 'evt_demo_host_ready_002', sold: 96, checkedIn: 0, revenue: 2720, status: 'published' },
  evt_demo_host_locked_003: { eventId: 'evt_demo_host_locked_003', sold: 138, checkedIn: 0, revenue: 6024, status: 'published' },
  evt_demo_host_nonprofit_004: { eventId: 'evt_demo_host_nonprofit_004', sold: 112, checkedIn: 0, revenue: 6100, status: 'published' },
  evt_demo_host_circle_005: { eventId: 'evt_demo_host_circle_005', sold: 88, checkedIn: 0, revenue: 6240, status: 'published' },
  evt_demo_host_soldout_006: { eventId: 'evt_demo_host_soldout_006', sold: 98, checkedIn: 0, revenue: 11150, status: 'published' },
  evt_demo_host_lowsales_007: { eventId: 'evt_demo_host_lowsales_007', sold: 31, checkedIn: 0, revenue: 792, status: 'published' },
  evt_demo_host_conference_008: { eventId: 'evt_demo_host_conference_008', sold: 174, checkedIn: 0, revenue: 33726, status: 'published' },
  evt_demo_host_past_report_009: { eventId: 'evt_demo_host_past_report_009', sold: 152, checkedIn: 139, revenue: 8200, status: 'ended' },
  evt_demo_host_past_preview_010: { eventId: 'evt_demo_host_past_preview_010', sold: 121, checkedIn: 104, revenue: 1825, status: 'ended' },
};

const now = new Date().toISOString();

export const MOCK_HOST_CLOSEOUT_REPORTS: CloseoutReport[] = [
  {
    id: 'closeout_evt_demo_host_past_report_009_seed',
    eventId: 'evt_demo_host_past_report_009',
    eventTitle: 'Completed: Jazz Garden Social',
    hostEmail: 'demo.host@getechoaccess.com',
    createdAt: now,
    checkedInCount: 139,
    remainingCount: 13,
    deniedCount: 4,
    attendanceRate: 76,
    attendeeList: Array.from({ length: 18 }, (_, index) => ({
      id: `seed_attendee_${index + 1}`,
      name: ['Maya Johnson', 'Alex Carter', 'Jordan Lee', 'Nia Brooks', 'Marcus Reed', 'Taylor Stone'][index % 6],
      ticket: index % 4 === 0 ? 'Reserved Table' : 'Garden Entry',
      status: index < 14 ? 'checked_in' as const : 'remaining' as const,
      time: index < 14 ? `${index + 2}m after open` : undefined,
    })),
    analytics: {
      totalCapacity: 184,
      noShowCount: 13,
      scanSuccessRate: 97,
      entryTrustScore: 94,
    },
    emailStatus: 'sent',
    availableDownloads: ['attendee_csv', 'attendance_pdf', 'event_analytics_pdf'],
  },
];

export const isDemoHostEvent = (eventId?: string | null) => !!eventId && eventId.startsWith(ECHO_DEMO_HOST_EVENT_PREFIX);
