# Generated by Django 5.2.15 on 2026-07-04 22:02

import core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_tickettier_access_tier'),
        ('identity', '0001_initial'),
        ('tickets', '0002_ticketcredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorSession',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('zone', models.CharField(choices=[('main_entry', 'main_entry'), ('vip_lounge', 'vip_lounge'), ('meet_and_greet', 'meet_and_greet'), ('backstage', 'backstage'), ('after_party', 'after_party'), ('sponsor_lounge', 'sponsor_lounge'), ('restricted_area', 'restricted_area'), ('green_room', 'green_room'), ('stage_access', 'stage_access'), ('operations_areas', 'operations_areas')], default='main_entry', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='active', max_length=16)),
                ('passcode_hash', models.CharField(max_length=128)),
                ('passcode_failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('passcode_locked_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='door_sessions', to='identity.device')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='door_sessions', to='events.event')),
                ('walkup_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='door_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoorScan',
            fields=[
                ('echo_id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField()),
                ('verification_state', models.CharField(max_length=32)),
                ('refusal_code', models.CharField(blank=True, default='', max_length=32)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=64)),
                ('ticket_status', models.CharField(max_length=16)),
                ('offline', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('live', 'Live'), ('reconcile', 'Reconcile')], default='live', max_length=16)),
                ('scanned_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='door_scans', to='events.event')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='door_scans', to='tickets.ticket')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='door.doorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket', 'approved', '-recorded_at'], name='scan_ticket_dup_idx'), models.Index(fields=['event', 'recorded_at'], name='scan_event_recorded_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'reconcile')), fields=('session', 'ticket', 'scanned_at'), name='uniq_reconciled_scan_entry')],
            },
        ),
    ]
