/**
 * ECHO Onboarding — Approved Copy
 * ═══════════════════════════════
 * Source of truth for onboarding strings (spec §22). Use these verbatim.
 * No surveillance/crypto/"frictionless omnichannel" language.
 */

export const ONBOARDING_COPY = {
  splash: {
    wordmark: 'ECHO',
    tagline: 'Access starts here.',
  },
  welcome: {
    title: 'Your access to better events.',
    title1: 'Premium access.',
    title2: 'Unforgettable events.',
    sub: 'Secure entry, effortless access, made for how you experience live.',
    body: 'Discover events, secure your pass, and enter with confidence.',
    primary: 'Get Started',
    secondary: 'Log In',
    trust: 'Wallet-first access. Secure. Private.',
  },
  circle: {
    eyebrow: 'Bring your circle',
    title1: 'Good plans are',
    title2: 'better together.',
    sub: 'Add friends, share the plan, and everyone gets in.',
    spotsClaimed: 'Spots Claimed',
    invite: 'Invite friends',
    inviteSub: 'They\u2019ll get a notification to join.',
    next: 'Next',
    skip: 'Skip',
  },
  choosePath: {
    title: 'What brings you to ECHO?',
    explore: { title: 'Explore Events', body: 'Find events near you.' },
    invite: { title: 'I Have an Invite', body: 'Claim a ticket, pass, or group spot.' },
    host: { title: 'Host Events', body: 'Create events and manage access.' },
  },
  discover: {
    title: 'Find events that match your energy.',
    body: 'ECHO helps you discover music, nightlife, food, community, premium, and local experiences.',
    skip: 'Skip',
    next: 'Continue',
  },
  accessDemo: {
    title: 'Try your ECHO Pass.',
    body: 'Your ECHO Pass keeps access ready when it\u2019s time to enter.',
    passLabel: 'Demo ECHO Pass',
    prompt: 'Tap to try',
    holdPrompt: 'Hold to enter',
    success: 'Access confirmed.',
    final: 'That\u2019s ECHO Access.',
    qrFallback: 'Use QR entry where NFC is not available.',
    next: 'Continue',
  },
  trust: {
    title: 'The right pass. The right person. The right event.',
    body: 'ECHO helps hosts verify access, manage entry, and protect tickets.',
    cards: {
      verified: { title: 'Verified passes', body: 'Tickets are checked before entry.' },
      ageGated: { title: 'Safer age-gated events', body: 'Age checks happen only when required.' },
      hostControlled: { title: 'Host-controlled access', body: 'Hosts and security can manage entry in real time.' },
    },
    sheetTrigger: 'What is the Trust Ring?',
    sheetBody:
      'The Trust Ring helps show that a pass, event, and access point are connected securely. Some events may require extra checks like age verification or host approval.',
    next: 'Continue',
  },
  eventEnergy: {
    eyebrow: 'Make it yours',
    title1: 'Events that fit',
    title2: 'your vibe.',
    sub: 'Tell us what you love and we\u2019ll curate better picks for you.',
    prompt: 'What are you into?',
    next: 'Next',
    nearby: 'Nearby Events',
    title: 'What\u2019s your event energy?',
    interestsTitle: 'Interests',
    groupTitle: 'How do you usually go out?',
    budgetTitle: 'Budget feel',
    locationTitle: 'Location',
    useLocation: 'Use current location',
    searchCity: 'Search city manually',
    primary: 'Build My ECHO',
    skip: 'Skip for now',
  },
  account: {
    title: 'Save your pass and preferences.',
    apple: 'Continue with Apple',
    google: 'Continue with Google',
    email: 'Continue with Email',
    guest: 'Continue as Guest',
    gate: 'Create an account to save this to your ECHO Pass.',
  },
  permissions: {
    title: 'Set up your event experience.',
    location: { title: 'Location', body: 'Find events near you.' },
    notifications: { title: 'Notifications', body: 'Get ticket updates, invite alerts, and event reminders.' },
    wallet: { title: 'Wallet', body: 'Add your ECHO Pass for faster access.' },
    notNow: 'Not Now',
    allow: 'Allow',
    next: 'Continue',
    fallback: {
      locationDenied: 'No problem. Choose a city instead.',
      notificationsDenied: 'You can still see tickets and updates in the app.',
      walletUnavailable: 'Your ECHO Pass is still available in the app.',
      nfcUnavailable: 'Use QR entry where NFC is not available.',
    },
  },
  echoPass: {
    eyebrow: 'Your ECHO Pass',
    title1: 'Tap in with',
    title2: 'confidence.',
    sub: 'Secure wallet-based access with fast, contactless entry.',
    next: 'Next',
    title: 'Meet your ECHO Pass.',
    body: 'Your pass keeps tickets, access, group claims, and check-in details in one place.',
    demoLabel: 'Demo ECHO Pass',
    nfcReady: 'NFC-ready',
    qrFallback: 'QR fallback',
    primary: 'Continue to ECHO',
    secondary: 'Add to Wallet Later',
    walletCta: 'Add to Wallet',
  },
  complete: {
    eyebrow: 'You\u2019re all set',
    title1: 'You\u2019re in.',
    title2: 'Let\u2019s go.',
    sub: 'Your account is ready and your pass is active.',
    primary: 'Start Exploring',
    secondary: 'Explore the app',
    status: {
      ageVerified: { title: 'Age Verified', done: 'You\u2019re verified to attend.', pending: 'Verify your age when an event requires it.' },
      entryReady: { title: 'Entry Ready', done: 'Your pass is active.', pending: 'Your pass activates with your first event.' },
      privateSecure: { title: 'Private & Secure', done: 'Your data is protected.', pending: 'Your data is protected.' },
    },
    title: 'Your first ECHO experience is ready.',
    body: 'Start with your picks, your pass, or your next invite.',
    cta: 'Explore My Picks',
  },
  resume: {
    title: 'Continue setting up ECHO?',
    continue: 'Continue',
    skip: 'Skip to Home',
    restart: 'Start Over',
  },
  firstAction: {
    title: 'Ready for your first ECHO moment?',
    saveEvent: 'Save this event',
    viewPicks: 'View your picks',
    addPass: 'Add your pass',
    claimInvite: 'Claim your invite',
    followHost: 'Follow this host',
  },
  recommendationLabels: {
    no_signal: 'Start with a few picks. ECHO gets better as you explore.',
    location_only: 'Popular near you.',
    interest_based: 'Curated from your event style.',
    behavior_based: 'Based on your recent interest.',
    purchase_based: 'Picked for You. Curated by ECHO AI.',
    mature_profile: 'Picked for You. Curated by ECHO AI.',
  },
} as const;

export type OnboardingCopy = typeof ONBOARDING_COPY;
